name: build
on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - 'index.js'
      - 'api/**'
      - 'test/**'
      - 'package.json'
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Test
      run: npm run test
      env:
        MWS_KEY_ID: ${{ secrets.MWS_KEY_ID }}
        MWS_KEY_SECRET: ${{ secrets.MWS_KEY_SECRET }}
        AMZ_EU_SELLER_ID: ${{ secrets.AMZ_EU_SELLER_ID }}