name: publish
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'index.js'
      - 'api/**'
      - 'package.json'
      - 'data/**'
      - 'README.md'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Publish to NPM
      uses: kaskadi/action-npmpub@master
      with:
        USERNAME: Alexis Lemaire
        EMAIL: a.lemaire@klimapartner.de
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        COMMIT_MSG: ${{ github.event.head_commit.message }}
